### ISSUE TITLE
Random latitude and longitude generator

### ISSUE THREAD

**Issue by Apsurt** [Apsurt/omni-geo-ai#1]
Write a script to generate any number of random coordinates (latitude, longitude).

These coordinates have to:
1. Be on land
2. Be in countries or territories where google street view is available:
Albania
Andorra
Argentina
Australia
Austria
Bangladesh
Belgium
Bhutan
Bolivia
Botswana
Brazil
Bulgaria
Cambodia
Canada
Chile
Colombia
Croatia
Czechia
Denmark
Dominican Republic
Ecuador
Estonia
Eswatini
Finland
France
Germany
Ghana
Greece
Greenland
Guatemala
Hungary
Iceland
Indonesia
Ireland
Israel
Italy
Japan
Jordan
Kenya
Kyrgyzstan
Latvia
Lesotho
Lithuania
Luxembourg
Malaysia
Mexico
Mongolia
Montenegro
Netherlands
New Zealand
Nigeria
North Macedonia
North Mariana Islands
Norway
Palestine
Panama
Peru
Philippines
Poland
Portugal
Romania
Russia
Senegal
Serbia
Singapore
Slovakia
Slovenia
South Africa
South Korea
Spain
Sri Lanka
Sweden
Switzerland
Taiwan
Thailand
Turkey
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
Uruguay
Egypt
Pakistan
China
Dominican Republic
India
Laos
Nepal
Rwanda
Vietnam
Bermuda
Puerto Rico
Réunion
Faroe Islands
Greenland (Denmark)
Hong Kong

**Comment by just-MG** [comment]
This can be done by randomly selecting coordinates and checking the free [Streetview Metadata API](https://developers.google.com/maps/documentation/streetview/metadata) to see if those coordinates are covered.

**Comment by Apsurt** [comment]
https://geoguessr.fandom.com/wiki/Countries_on_Geoguessr**

**credible source
